version: '3' 

services: 
    frontend:  
      image: frontend
      build: frontend
      container_name: frontend
      ports: 
        - 5000:5000

    backend:             
      image: backend
      build: backend
      container_name: backend
      environment: 
        - REDIS=redis-cache
        - REDIS_PORT=6379
      ports: 
        - 8000:8000
    
    redis-cache:
      image: redis
      build: redis-cache
      container_name: redis-cache

