version: '3' 

services: 

    proxy:
      build: ./proxy
      image: proxy
      volumes:
        - /var/run/docker.sock:/tmp/docker.sock:ro
      ports:
        - 80:80
      container_name: proxy
      volumes:
        - "./nginx.conf:/etc/nginx/nginx.conf"
        - /var/run/docker.sock:/tmp/docker.sock:ro

    frontend:  
      image: frontend
      build: frontend
      container_name: frontend
      ports: 
        - 5000:5000

    backend:             
      image: backend
      build: backend
      container_name: backend
      environment: 
        - REDIS=redis-cache
        - REDIS_PORT=6379
        - DB_USERNAME=backenduser
        - DB_PASSWORD=VerySecret1
        - DB_NAME=backend_db
        - DB_HOST=db
    
      ports: 
        - 8000:8000
    redis-cache:
      image: redis
      build: redis-cache
      container_name: redis-cache

    db:
      image: postgres
      restart: unless-stopped
      environment:
        - POSTGRES_DB=backend_db
        - POSTGRES_USER=backenduser
        - POSTGRES_PASSWORD=VerySecret1
      container_name: backend_db
    
